# Generated by Django 5.0.6 on 2024-10-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diaporama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(choices=[('Réunion', 'Réunion'), ('Fête', 'Fête'), ('Décès', 'Décès')], default='Réunion', max_length=50)),
                ('intitule', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='diaporama/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.IntegerField()),
                ('secretaire', models.IntegerField()),
                ('secretaire_adjoint', models.IntegerField()),
                ('tresorier', models.IntegerField()),
                ('tresorier_adjoint', models.IntegerField()),
                ('conseiller_1', models.IntegerField()),
                ('conseiller_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='bureau/ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(choices=[('Réunion', 'Réunion'), ('Fête', 'Fête'), ('Décès', 'Décès')], default='Réunion', max_length=50)),
                ('intitule', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
